[application]

[web.app]

# HTML title tag content
title = "Weaver"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = ["assets/sw.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
